### ISSUE TITLE
JsonReaderException if entire secret value is an array of json

### ISSUE THREAD

**Issue by udlose** [Kralizek/AWSSecretsManagerConfigurationExtensions#21]
If you create a Secret with a PlainText value that is an array of json, you will receive a JsonReaderException:

>            Newtonsoft.Json.JsonReaderException: "Error reading JObject from JsonReader. Current JsonReader item is not an object: StartArray. Path '', line 1, position 1."

This is caused by the use of `JObject.Parse()` on the given value before it is determined whether or not it is an array.  The correct solution is to use `JToken.Parse()` instead.
 
Example:
```
[{
  "Name": "John",
  "Age": 21
},
{
  "Name": "Mary",
  "Age": 22
}]
```

**Comment by Kralizek** [comment]
Hey @udlose, thank you for opening this issue and making the PR.

It all seems good but before I merge it, I'd like you to edit the open post of this issue with a sample of the json snippet that could be used to recreate the issue.

**Comment by Kralizek** [comment]
I'm releasing version 1.2.1 with the fix of this issue.
