### ISSUE TITLE
Refreshing provider with updated (rotated) secrets

### ISSUE THREAD

**Issue by KevM** [Kralizek/AWSSecretsManagerConfigurationExtensions#23]
🥇 Thank you for this configuration extensions provider! 🥇 

It seems that there are [reload capabilities in the configuration extensions](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.configuration.configurationprovider.getreloadtoken?view=dotnet-plat-ext-3.1#Microsoft_Extensions_Configuration_ConfigurationProvider_GetReloadToken) that are up to the provider to implement.  

[Example for a cloud api](https://github.com/qinezh/Microsoft.Extensions.Configuration.AzureBlob/blob/master/AzureBlobConfigurationExtension/BlobJsonConfigurationProvider.cs)

Do you have any thoughts about adding support for this to your provider?

**Comment by Kralizek** [comment]
Hi @KevM, it would be an interesting addition. Unfortunately I don't have enough knowledge of configuration providers with reload capabilities so it will take a while before I can produce something.

I would gladly welcome a pull request both to implement the feature or just show the basic way.

**Comment by KevM** [comment]
Ok. I can look into this for the long term if we continue to us this nuget.
Currently we are running into a blocker given that we need our
dependencies to be signed.

**Comment by Kralizek** [comment]
Fixed by #27
