### ISSUE TITLE
Package dependency conflicts

### ISSUE THREAD

**Issue by sol-wasserman** [Kralizek/AWSSecretsManagerConfigurationExtensions#40]
Nuget refuses to add this package as a dependency because: `NU1107: Version conflict detected for AWSSDK.Core. Install/reference AWSSDK.Core 3.5.1.54 directly to resolve this issue. Kralizek.Extensions.Configuration.AWSSecretsManager 1.4.1 -> AWSSDK.SecretsManager 3.3.0 -> AWSSDK.Core (>= 3.3.21.20 && < 3.4.0)`.

And when referencing the latest `AWSSDK.Core` package directly, Nuget would warn when restoring that `Detected package version outside of dependency constraint: AWSSDK.SecretsManager 3.3.0 requires AWSSDK.Core (>= 3.3.21.20 && < 3.4.0) but version AWSSDK.Core 3.5.1.56 was resolved.`.

This makes it complicated to consume this package if one uses any other AWS package in their projects.

**Comment by Kralizek** [comment]
Hi, have you tried pinning the latest version of AWSSDK.SecretsManager in your project file?

**Comment by sol-wasserman** [comment]
It solved the issue, thank you!

**Comment by udlose** [comment]
> Hi, have you tried pinning the latest version of AWSSDK.SecretsManager in your project file?

@Kralizek can you please clarify what this means?  Is there a special syntax or order of dependencies in the .csproj?  I've never heard of "pinning" a reference

**Comment by Kralizek** [comment]
> > Hi, have you tried pinning the latest version of AWSSDK.SecretsManager in your project file?
> 
> @Kralizek can you please clarify what this means?  Is there a special syntax or order of dependencies in the .csproj?  I've never heard of "pinning" a reference

Hi! Check the pinned issue :)
