### ISSUE TITLE
Reloading configuration without polling

### ISSUE THREAD

**Issue by TheRubble** [Kralizek/AWSSecretsManagerConfigurationExtensions#41]
I've got a use case where I need to reload configuration but don't wish to use polling (In a particular sensitive code base where performance etc. is everything).

```
SecretsManagerConfigurationProvider.cs

public Task ForceReloadAsync(CancellationToken cancellationToken)
{
    return ReloadAsync(cancellationToken);
}
```

Would you have an objections if I raised this as a PR? I chose to go down adding the new method rather than opening up the access to the existing method so I'd clearly show the intent.

**Comment by Kralizek** [comment]
Please do open a PR but, before committing to merge it in, I want to give a look at the changes you suggest.

**Comment by TheRubble** [comment]
As requested : https://github.com/Kralizek/AWSSecretsManagerConfigurationExtensions/pull/42

**Comment by Kralizek** [comment]
Hi @TheRubble

Thank you for the PR!

I have a feeling that the Configuration stack already has support for on-demand reload.

Did you check if `IOptionsSnapshot` works for your case?

https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/options?view=aspnetcore-5.0#use-ioptionssnapshot-to-read-updated-data

I haven't tried it myself, but if I understand the sample correctly, the providers should be requested for a new configuration every time you use the `Value` property.

Please let me know if this approach works for your case.

**Comment by TheRubble** [comment]
So I don't think that'll work, IOptionsSnapshot is the correct mechanism and would work if I was using the polling support in the library as that looks like it's triggering the ReloadToken hence telling the interested consumers that the configuration has changed. 
However because

**Comment by Kralizek** [comment]
Interesting.

How would you bind the new method to the monitor and the snapshot?

**Comment by TheRubble** [comment]
I don't believe I need to, the underlying plumbing appears to register against the reload token from the configuration provider and hence knows when it's been triggered.

**Comment by Kralizek** [comment]
But your `ForceReloadAsync` is not part of any interface, is it? How would it be called from the Configuration infrastructure?

**Comment by TheRubble** [comment]
It's not. The flow is ```ForceReloadAsync > ReloadAsync > FetchConfigurationAsync > SetData(triggerReload : true) > OnReload```. The OnReload function : 

```
protected void OnReload()
{
    var previousToken = Interlocked.Exchange(ref _reloadToken, new ConfigurationReloadToken());
    previousToken.OnReload();
}
```

When that token is triggered AFAIK the stack above then knows that the underlying data has changed and it can then reload etc.

To call ForceReloadAsync I'd have to get the instance out of the IOC container.

**Comment by TheRubble** [comment]
Hi @Kralizek,

Any further thoughts? 

Thanks

**Comment by Kralizek** [comment]
Hey! Sorry for disappearing. It's been holiday times here so I haven't spent much time on GitHub in general.

As soon as I have some time I'll try your PR and give some feedback. :)

**Comment by TheRubble** [comment]
Anything I can do to move this forward?

**Comment by Kralizek** [comment]
Hey @TheRubble,

sorry for the delay. I wanted to investigate alternative ways but I couldn't find any that was really better than the suggested solution.

I'll merge your PR in.
