### ISSUE TITLE
Upgrade to latest SDK

### ISSUE THREAD

**Issue by armitagemderivitec** [Kralizek/AWSSecretsManagerConfigurationExtensions#43]
Is it possible to upgrade this package to use the latest AWSSDK packages?

We have upgraded to the latest versions and now have a lot of build warning because of the upper constraint of version 3.4 on AWSSDK.Core.

**Comment by Kralizek** [comment]
Hi @armitagemderivitec,

Please check if the solution shown in the issue #40 helps your case.

**Comment by armitagemderivitec** [comment]
Sorry to waste your time! I don't know why this didn't occur to me.

**Comment by Kralizek** [comment]
Added pinned issue #45
