### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by nathanaelk** [Kralizek/AWSSecretsManagerConfigurationExtensions#44]
Current version of AWSSDK.SecretsManager (3.3.0)  requires AWSSDK.Core versions between 3.3.21.20 & 3.4.0. We had to downgrade a lot of AWSSDK.* packages to prevent incompatibility. Would it be possible to update the dependencies to the latest versions available. I tried and successfully an all the tests on them.
Will also be more than happy to help with maintaining the repo.

**Comment by Kralizek** [comment]
Hi @nathanaelk 

Please check if the solution shown in the issue #40 helps your case.

**Comment by nathanaelk** [comment]
Hey @Kralizek ,
the solution from issue #40 works for me.  Thank you for the prompt response and for making this package available for all of us

**Comment by Kralizek** [comment]
I'm glad it worked. Would you please give a look at the issue I just pinned and let me know if it's not clear enough for others having the same issue in the future?

**Comment by nathanaelk** [comment]
Looked at #45 and it looks great. May be worth adding a reference to it in the README.
Thanks again.

**Comment by Kralizek** [comment]
Good idea, in the meantime I will close this issue :)
