### ISSUE TITLE
Secrets that look like Json Arrays or Objects (but are not) do not work

### ISSUE THREAD

**Issue by mirkogeffken** [Kralizek/AWSSecretsManagerConfigurationExtensions#48]
Secrets that look like arrays or objects (start with "[" or "{"), but are not actually Json do not work. e.g. a secret being "{THIS IS NOT AN OBJECT" or "[THIS IS NOT AN ARRAY" do not work. There is a function in the source checking for the value starting with these called IsJson, which is probably too simplistic a check (maybe JToken.Parse and check for JsonReaderException instead)?

**Comment by Kralizek** [comment]
Hi @mirkogeffken, thank you for opening this issue. Do you want to give a try at tackling this issue?
