### ISSUE TITLE
Async loading causes blocking during test execution

### ISSUE THREAD

**Issue by rgmills** [Kralizek/AWSSecretsManagerConfigurationExtensions#5]
👋 I'm back!

I've been updating our integration tests (after a couple months of neglect) and encountered an issue with using this configuration provider.  A decent description of the issue (and how to reproduce) is available at https://github.com/aspnet/Configuration/issues/783 .  In short, when using xunit test collections and having multiple, it tends to create a deadlock while attempting to load configuration settings.

The only way I've found to make this work is doing a bad thing and updating the calls to `IAmazonSecretsManager` to force synchronous execution by using `GetAwaiter().GetResult()`.  What would be your thoughts on switching to this?

Thanks!

**Comment by rgmills** [comment]
Actually, may just need to ConfigureAwait all of the async calls to ISecretManager. I'll double check. I tried, but perhaps I didn't hit all of the API calls.

**Comment by Kralizek** [comment]
Hi @rgmills, sorry for the delay.

Do you think you can make a PR where all the awaited calls are `ConfigureAwait(false)`ed ?

**Comment by rgmills** [comment]
Hey, absolutely. I will get something up today. I think in my testing just ConfigureAwait(false) was sufficient. Triple checking then I'll open a PR.
