### ISSUE TITLE
Question on using SecretsManagerConfigurationProviderOptions.PollingInterval

### ISSUE THREAD

**Issue by a-milburn** [Kralizek/AWSSecretsManagerConfigurationExtensions#55]
I have set the PollingInterval with the intention that it refreshes the configuration values on a timed interval. I need this feature as our key rotation service refreshes the database password at regular intervals.

My assumption is that Entity Framework would pick up the new database credentials...but apparently, it does not. I had to go in and manually restart the service in order for it to pick up the new credentials.

Is there something else that I need to do in order for this process to run as intended? 

I have the following code:

` opts.PollingInterval = TimeSpan.FromMinutes(1)`

**Comment by Kralizek** [comment]
I would say it depends on how you registered EF and if it pulls the fresh configuration every time a context is created.

**Comment by a-milburn** [comment]
Yeah, doesn't appear to be a way of changing this behaviour.
