### ISSUE TITLE
Document that `AcceptedSecretArns` supports friendly names & partial ARN's

### ISSUE THREAD

**Issue by kpenergy** [Kralizek/AWSSecretsManagerConfigurationExtensions#59]
The `SecretsManagerConfigurationProviderOptions.AcceptedSecretArns` property's name suggests that it only supports full ARN's. However, the value's specified here are used as the `SecretId` in a `GetSecretValueRequest`, which means they can be:
- Full ARN (including random 6 characters at end)
- Partial ARN (excluding random 6 characters at end)
- Friendly Name

It would be good if either:
- The property name could be updated to remove the word ARN, since it's not specific to ARNs (I doubt this is a feasible option since it's a breaking change).
- Add XML documentation on this property (and ideally, on all properties, methods etc).
- Add more information in the [relevant README section](https://github.com/Kralizek/AWSSecretsManagerConfigurationExtensions#defining-list-of-secrets-in-advance-no-list-secrets-permission-required) to let users know what can be used here

**Comment by Kralizek** [comment]
Hi @kpenergy 

Thanks for opening this issue. Right now I don't have the time to invest in this library but I welcome contributors to propose changes with PRs: this applies both to the source code and to the documentation.

**Comment by kpenergy** [comment]
@Kralizek No worries, I'll try and submit an update to the docs over the next few days.

**Comment by devklick** [comment]
Created PR #60 to update docs and comments
