### ISSUE TITLE
Not merging options

### ISSUE THREAD

**Issue by marknadig** [Kralizek/AWSSecretsManagerConfigurationExtensions#62]
I hope this is something simple I'm missing.  It appears that the settings coming from Secrets Manager aren't merged under the same key from appsettings.json.

In my appsettings.json I have this
`  
"JWT": {
    "ValidAudience": "http://localhost:4200",
    "ValidIssuer": "http://localhost:61955"
  },
`

In AWS Secrets Manager I've got a secret named "MyBrokerDev" that contains a number or key/values:
`
{
  "Database__ConnectString": "...",
  "JWT__Secret": "ThisIsTheJWTSecret"
}
`

my KeyGenerator does replace "___" with ":".

My `JWTOptions` class has "ValidAudience", "ValidIssuer" and "Secret" properties all as `[Required]` attributes . I validate those attributes when loaded. When loading from my Elastic Beanstalk environment, the validation is failing with "System.ComponentModel.DataAnnotations.ValidationException: The Secret field is required.".

I've added a dump of all the settings the ConfigureServices :

`
var root = (IConfigurationRoot)Configuration;
logger.LogInformation($"Config: {root.GetDebugView()}");
`

Curiously, it renders as if there are two JWT sections:
```
Nov  9 17:01:33 ip-172-31-28-236 web: JWT:
Nov  9 17:01:33 ip-172-31-28-236 web: Secret=ThisIsTheJWT (SecretsManagerConfigurationProvider)
Nov  9 17:01:33 ip-172-31-28-236 web: JWT:
Nov  9 17:01:33 ip-172-31-28-236 web: ValidAudience=http://localhost:4200 (JsonConfigurationProvider for 'appsettings.json' (Optional))
Nov  9 17:01:33 ip-172-31-28-236 web: ValidIssuer=http://localhost:61955 (JsonConfigurationProvider for 'appsettings.json' (Optional))
```

locally, when I run this with an environment variable "JWT__Secret" = "ThisIsTheJWT", the same dump of settings appears to show them merged:
```
JWT:
   Secret=ThisIsTheJWTSecret (EnvironmentVariablesConfigurationProvider)
   ValidAudience=http://localhost:4200 (JsonConfigurationProvider for 'appsettings.Development.json' (Optional))
   ValidIssuer=http://localhost:61955 (JsonConfigurationProvider for 'appsettings.Development.json' (Optional))
```

Any ideas?

**Comment by marknadig** [comment]
After looking more, I do see the that it seems the secrets from Secrets Manager seem to be prefixed with the secret name. e.g. My secret name is MyBrokerDev and contains raw:
`{ "Database__ConnectString": "...", "JWT__Secret": "ThisIsTheJWTSecret" }`

The configuration variables from SM appear to be nested beneath "MyBrokerDev"; e.g.
```{ "MyBrokerDev" :  {
      "Database__ConnectString": "...", 
      "JWT__Secret": "ThisIsTheJWTSecret" }
    }
}```

That would explain why they're not "merged" because one is "JWT: Secret" and the other is considered "MyBrokerDev: JWT: Secret"

**Comment by marknadig** [comment]
Seems this is by design that the secret name is prepended. In my KeyGenerator I now strip it
```
private static string NormalizeKey(Amazon.SecretsManager.Model.SecretListEntry entry, string key)
{
    var prefix = entry.Name + ":";
    if (key.StartsWith(prefix)) {
        key = key[prefix.Length..];
    }
    // They keys for key/value pairs cannot contain ":", so we assume "__" is used and we'll replace here.
    return key.Replace("__", ":");
}
```

**Comment by Kralizek** [comment]
Hi @marknadig sorry for the slow answer. I'm happy you found a solution to your issue before I could intervene. Please let me know if you have more questions.

**Comment by marknadig** [comment]
Not at all @Kralizek , I sympathize with maintainers.
I appreciate you making your library open source.
