### ISSUE TITLE
Update for .NET Core 6?

### ISSUE THREAD

**Issue by rhires** [Kralizek/AWSSecretsManagerConfigurationExtensions#63]
Hello - can the sample code get updated for .NET Core 6, since the Startup and Program.cs files are not one in the same, and this all looks different now. Thanks!

**Comment by Kralizek** [comment]
Hi, I currently don't have the time.

The implementation is pretty simple, you can look at this amazing post by Andrew Lock: https://andrewlock.net/exploring-dotnet-6-part-1-looking-inside-configurationmanager-in-dotnet-6/

If you want, I'd gladly accept a PR that adds a sample based on a .NET 6 application.

**Comment by rhires** [comment]
Thanks! I'll have to finish reading all of Andrew Lock's posts first lol - 

I was also thinking that there might be a way to "genericize" this in such a way that it can be added to .NET Core to be the other half of secrets management (The first being `AddUserSecrets()`). That way when running as a given user in IIS or nginx (or whatever), it can grab the secrets from the external secrets store like AWS or Azure or something else that gets set up for that purpose. 

I'm mentioning this because some time ago I raised the issue of how to move from the internal user secrets used in development to how it's handled in production, and there were no good answers at the time. And your library is a great answer! So this is me now dreaming of having the time to implement something like this in a generic and good enough way that the main .NET Core could adopt it.
