### ISSUE TITLE
Replace Newtownsoft with System.Text.Json

### ISSUE THREAD

**Issue by goenning** [Kralizek/AWSSecretsManagerConfigurationExtensions#68]
If I contributed with a PR to replace newtownsoft json with System.Text.Json, would you accept it?

**Comment by Kralizek** [comment]
This could be an interesting development. I wonder if replacing is the right way to go. An alternative would be to mirror the package with support for STJ instead of NSJ. just thinking aloud.

**Comment by goenning** [comment]
But in that case, what would be the benefits of using NSJ instead of STJ though? Microsoft has been moving all their packages to use STJ, it's faster and comes pre-installed on .net core 3+.

From my perspective, removing NSJ from this packages means there's one less dependency on .net apps: smaller builds/images, faster deployments, etc.

**Comment by Kralizek** [comment]
I see your point and I agree with you. I'm just trying to find a way to hold from releasing a major version unless it's really needed.

**Comment by jcanady20** [comment]
I have a working PR that addresses this.

**Comment by Kralizek** [comment]
Closing since it was fixed with #71
