### ISSUE TITLE
Release non-prerelease version

### ISSUE THREAD

**Issue by elevate-andrewlock** [Kralizek/AWSSecretsManagerConfigurationExtensions#7]
Hi, thanks for this package - does exactly what I needed, and meant I didn't need to write the same thing!

I just have one request - please could you do a 1.0.0 release (i.e. not alpha)? Currently, if you try and reference this package from another (non pre-release) library you'll get warnings when packing NuGet packages: 

```
C:\Program Files\dotnet\sdk\2.1.302\Sdks\NuGet.Build.Tasks.Pack\buildCrossTargeting\NuGet.Build.Tasks.Pack.targets(198,5): warning NU5104: A stable release of a package should not have a prerelease dependency. Either modify the version spec of dependency "Kralizek.Extensions.Configuration.AWSSecretsManager [1.0.0-alpha-2, )" or update the version field in the nuspec.
```

Thanks! 🙂

**Comment by Kralizek** [comment]
Hi! Thanks for the comment. I kept the package in pre-release because I never had time to finalize the API and the feature set.

On the other hand I haven't had any concrete idea for a while. So I might as well remove the alpha tag.

Right now I'm still on vacation. Would you mind push a PR?

**Comment by elevate-andrewlock** [comment]
That makes sense - I've done the same thing before 🙂 You can always do new releases if those concrete ideas come back to you! 

I've raised a PR, thanks, but enjoy your vacation!
