### ISSUE TITLE
What IAM permissions are needed for this to work?

### ISSUE THREAD

**Issue by jxwaters** [Kralizek/AWSSecretsManagerConfigurationExtensions#76]
I get this error message:

Amazon.SecretsManager.AmazonSecretsManagerException: User: [obfuscated] is not authorized to perform: secretsmanager:ListSecrets because no permissions boundary allows the secretsmanager:ListSecrets action

I have verified the user has Allow: secretsmanager:ListSecrets

**Comment by Kralizek** [comment]
Uhm, not sure about the boundaries. But the library requires ListSecrets and GetSecretValue (going by memory, I'll check once at the office).

Could you write here the relevant (properly obfuscated) policy?

Also, it might be a good addition to the readme to mention the required permissions.

**Comment by avalara-stephen-hickey** [comment]
You may also need the `kms:Decrypt` permission if the secret is encrypted using a customer-managed key.
