### ISSUE TITLE
The code is using ListSecrets even though I have both defined AcceptedSecretArns and SecretsFilter

### ISSUE THREAD

**Issue by jxwaters** [Kralizek/AWSSecretsManagerConfigurationExtensions#78]
When deployed to AWS, it fails calling

 Kralizek.Extensions.Configuration.Internal.SecretsManagerConfigurationProvider.FetchAllSecretsAsync(CancellationToken cancellationToken)

With error

---> Amazon.SecretsManager.AmazonSecretsManagerException: User: arn:aws:sts::***REDACTED** is not authorized to perform: secretsmanager:ListSecrets because no identity-based policy allows the secretsmanager:ListSecrets action

How do I get it to only get the requested secrets?

I am using partial ARNs (just the unique keynames - is that why?

**Comment by Kralizek** [comment]
As it is right now, the secretsmanager:ListSecrets API is invoked at least once. I can see why this could be an unexpected behavior and I think it's ok marking it as a bug or anyway something that can be fixed within the scope of the 2.0 release.

https://github.com/Kralizek/AWSSecretsManagerConfigurationExtensions/blob/6c8d0393a75cfdae0462fad5849920f15cb4f60d/src/Kralizek.Extensions.Configuration.AWSSecretsManager/Internal/SecretsManagerConfigurationProvider.cs#L182-L205

**Comment by jxwaters** [comment]
Actually, it was user error, it DOES work with AcceptedSecretARNs defined.

   if (Options.AcceptedSecretArns.Count > 0) 
     { 
         return Options.AcceptedSecretArns.Select(x => new SecretListEntry{ARN = x, Name = x}).ToList(); 
     }
