### ISSUE TITLE
Newtonsoft.Json is a dependency

### ISSUE THREAD

**Issue by heunetik** [Kralizek/AWSSecretsManagerConfigurationExtensions#85]
Hello,

Currently the NuGet package lists `Newtonsoft.Json (>= 13.0.1)` [as a dependency](https://www.nuget.org/packages/Kralizek.Extensions.Configuration.AWSSecretsManager#dependencies-body-tab).

Based on PR #71, it should not be in use, although it is still referenced in the [`Test` .csproj](https://github.com/Kralizek/AWSSecretsManagerConfigurationExtensions/blob/b3a8a7a6bb1e6452b189ae78745c64bc211bfe25/tests/Tests.Extensions.Configuration.AWSSecretsManager/Tests.Extensions.Configuration.AWSSecretsManager.csproj#L19) and used in the [`SecretsManagerConfigurationProviderTests.cs` test class](https://github.com/Kralizek/AWSSecretsManagerConfigurationExtensions/blob/b3a8a7a6bb1e6452b189ae78745c64bc211bfe25/tests/Tests.Extensions.Configuration.AWSSecretsManager/Internal/SecretsManagerConfigurationProviderTests.cs#L7).

Is there a specific reason to keep using the `Newtonsoft.Json` in that class, or it's just a leftover from the `System.Text.Json` migration?

Version: 1.7.0

**Comment by Kralizek** [comment]
The migration to STJ was merged but not released, this is why 1.7.0 still references NJ.

As for the tests, it shouldn't matter as unit tests are not reflected in the package.

**Comment by heunetik** [comment]
Thank you for the quick answer, all clear now!
