### ISSUE TITLE
How to configure secrets manager when retrieving via IAM role?

### ISSUE THREAD

**Issue by lbelloq** [Kralizek/AWSSecretsManagerConfigurationExtensions#89]
One of our apps will consume an AWS secrets vault, and as it runs via Kubernetes, the associated service account will be assigned an IAM role. Question is, how do I configure my app with this library in order to successfully retrieve the secrets? With classic credentials, the code is straightforward:

```csharp
Host.CreateDefaultBuilder(args)
    .ConfigureAppConfiguration((ctx, builder) =>
    {
        var c = builder.Build();
        var region = c.GetValue<string>("AWS_SECRETS_REGION");
        var name = c.GetValue<string>("AWS_SECRETS_NAME");
        var creds = new EnvironmentVariablesAWSCredentials(); //using environment variables for client ID and secret
        var configurator = new Action<SecretsManagerConfigurationProviderOptions>(opts =>
        {
            opts.SecretFilter = entry =>
            {
                return string.Equals(entry.Name, name, StringComparison.InvariantCulture);
            };
        });
        builder.AddSecretsManager(credentials: creds, region: RegionEndpoint.GetBySystemName(region), configurator: configurator);
    })
```

but I don't know how to do it when using an IAM role.

**Comment by Kralizek** [comment]
This is more of a question for how to use the AWS SDK than related to this library.

Anyway, this old blog post of mine might help you in that direction: https://renatogolia.com/2023/02/15/developing-secure-dotnet-application-using-iam-roles/

**Comment by lbelloq** [comment]
Found it. 

In case someone has a similar problem, turns out you don't actually have to configure credentials in your code; the service account will do all the heavy lifting.

Thank you, @Kralizek , for your time.
