### ISSUE TITLE
Use default region from credentials

### ISSUE THREAD

**Issue by pontusr** [Kralizek/AWSSecretsManagerConfigurationExtensions#9]
Thanks for your work on this - replaced my own code with yours.

I would like to avoid specificying the region in code as this may change between development and production environments (for example).

As it cumbersome and anti-pattern to read a value from the configuration object during application configuration I would prefer if the region was using the default region (from the credentials profile).
I believe this should then work fine on development machines, EC2 instances and Lambdas.

I'm happy to create a PR for this if you think it makes sense as well.

**Comment by geedsen** [comment]
Not an issue but a request , suggestion. Would it be possible to add a AddUserSecretsManager that would use the current region, the region the current instance is running in? If it is possible to obtain that, I haven't found a way yet. Thanks

**Comment by jabberwik** [comment]
As a workaround, you can get the default region with `Amazon.Runtime.FallbackRegionFactory.GetRegionEndpoint()` and pass that into your config.
