### ISSUE TITLE
Update nuget package AWSSDK.SecretsManager to latest version to support EKS Pod Identities. 

### ISSUE THREAD

**Issue by juanchovelezpro** [Kralizek/AWSSecretsManagerConfigurationExtensions#91]
AWS released a new version of nuget packages supporting EKS Pod Identities -> https://github.com/aws/aws-sdk-net/discussions/3126#discussioncomment-8256670

Updating the nuget package to its latest version we can use that new feature.

**Comment by Kralizek** [comment]
Please refer to #45 on how to use the latest version of the AWS SDK for .NET assemblies.
